[workspace]
members = [
    "day1",
]

[workspace.dependencies]
rand = "0.8.5"
uuid = { version = "^1.3.3", features = ["v4", "v7"]}
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html